postprocessor:
  APS_mode: true
  name: weiper_kldiv
  postprocessor_args:
    n_repeats: 100
    lambda_1: 2.5
    lambda_2: 0.1
    n_bins: 100
    perturbation_distance: 2.1
    smoothing: 4
    smoothing_perturbed: 15
    exact_minmax: true
    n_samples_for_setup: 300000
    start_epoch: 100
    end_epoch :  100
    fc_dir: /home/omar/weiper/Weiper/checkpoints/fc_layers

  postprocessor_sweep:
    lambda_1_list:
    - 0.1
    - 1
    - 2.5
    - 4
    lambda_2_list:
    - 0.1
    - 0.25
    - 1
    - 2.5
    - 5
    n_bins_list:
    - 60
    - 80
    - 100
    perturbation_distance_list:
    - 1.8
    - 2.0
    - 2.2
    - 2.4
    smoothing_list:
    - 4
    - 8
    - 12
    - 20
    - 40
    smoothing_perturbed_list:
    - 15
    - 25
    - 40
